version: '3.7'

services:
  tp1-es2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: tp1-es2
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev